### PR TITLE
Fixed porting issues

### PR DESCRIPTION
**Pull request by SecurityOfThings2016**
1. Correct visor recursive clone issue.
2. changed github urls to https to fix git clone issues.
These fixes are tested before requesting pull request.

### CODE REVIEW

**Comment by ciarmcom** [comment]
Automatic CI verification build not done, please verify manually.

**Comment by ciarmcom** [comment]
Automatic CI verification build not done, please verify manually.

**Comment by ciarmcom** [comment]
Automatic CI verification build not done, please verify manually.

**Comment by SecurityOfThings2016** [comment]
These fixes are tested before requesting pull request.

**Comment by meriac** [comment]
Duplicate of https://github.com/ARMmbed/uvisor/issues/134

**Pull request closed without merging**
