### PR TITLE
Added simple round-robin region virtualization

### PR DESCRIPTION
**Pull request by meriac**
@AlessandroA

### CODE REVIEW

**Comment by miklis** [comment]
Build finished. No test results found.

**Comment by miklis** [comment]
Build finished. No test results found.

**Comment by miklis** [comment]
Build finished. No test results found.

**Comment by miklis** [comment]
Build finished. No test results found.

**Comment by miklis** [comment]
Build finished. No test results found.

**Comment by miklis** [comment]
Build finished. No test results found.

**Comment by miklis** [comment]
Build finished. No test results found.

**Comment by miklis** [comment]
Build finished. No test results found.

**Comment by AlessandroA** [comment]
+1

**Comment by miklis** [comment]
Build finished. No test results found.

**Pull request merged**
