### PR TITLE
fixed MMFAR bug - showed prevoius fault address

### PR DESCRIPTION
**Pull request by meriac**
@AlessandroA @jserv @georgekang
This bug did hide the true source of issue 20 in uvisor hello world. The HAL_Init function needs to be fixed, too.

(see also https://github.com/ARMmbed/uvisor-helloworld/issues/20)

### CODE REVIEW

**Comment by miklis** [comment]
Build finished. No test results found.

**Comment by AlessandroA** [comment]
Referencing the issue just for completeness https://github.com/ARMmbed/uvisor-helloworld/issues/20

**Comment by miklis** [comment]
Build finished. No test results found.

**Comment by AlessandroA** [comment]
+1

**Comment by miklis** [comment]
Build finished. No test results found.

**Pull request merged**
