### PR TITLE
Updated QUICKSTART.md 

### PR DESCRIPTION
**Pull request by sherrellbc**
QUICKSTART.md does not work by default. There should be an explicit step to checkout a working release of mbed-os (see [here](https://github.com/ARMmbed/mbed-os/issues/2533)). In addition to this, a uVisor ACL was missing for the PIT causing the example blinky code to not work.

I did not check if the later secure box example requires more ACL changes -- this is just a patch to get the blinky code to work.

### CODE REVIEW

**Comment by mazimkhan** [comment]
retest uvisor

**Comment by mazimkhan** [comment]
retest uvisor

**Comment by mazimkhan** [comment]
retest uvisor

**Comment by meriac** [comment]
@sherrellbc Please sign the contributor license agreement in your mbed.com account.

**Comment by meriac** [comment]
@sherrellbc please ping me once the CLA is signed, happy to re-open.

**Pull request closed without merging**
