### PR TITLE
Add initial clang-format file

### PR DESCRIPTION
**Pull request by Patater**
This file attempts to describe our coding standard in a way that
clang-format understands. It isn't perfect yet, but it is a nice
starting point.

See <http://clang.llvm.org/docs/ClangFormat.html> for usage
instructions, including how to integrate clang-format with your favorite
text editor.

@AlessandroA @niklas-arm @meriac

### CODE REVIEW

**Comment by AlessandroA** [comment]
Thanks! I think it's a great start, I've been using it lately. Could you add here (in the PR description and in the commit description) a one-line how-to to use it on a particular file/set of files?

When the file is mature enough we can think of ways to hook it in the contribution process or in the build process.

**Comment by Patater** [comment]
Updated commit description to point to clang-format documentation.

**Comment by Patater** [comment]
I've been using clang-format with my text editor to, from time to time, auto-format highlighted blocks of code.

**Comment by meriac** [comment]
@Patater : please rebase

**Comment by Patater** [comment]
@meriac: Rebased

**Pull request merged**
