### PR TITLE
Handle 128th character dropping issue

### PR DESCRIPTION
**Pull request by orenc17A**

### CODE REVIEW

**Comment by niklas-arm** [comment]
One could probably also implement this by checking length against `(DEBUG_MAX_BUFFER - 2)` and then not overwriting the data. But this works fine too. cc @Patater.

**Comment by Patater** [comment]
Yeah, I'd find that easier to read than the current implementation.

**Comment by orenc17A** [comment]
retest uvisor

**Comment by orenc17A** [comment]
@niklas-arm  @Patater 
could you please review the new implementation

**Comment by orenc17A** [comment]
Done

**Pull request merged**
